server:
  port: ${PORT:8081}
  tomcat:
    threads:
      max: 20000
  servlet:
    context-path: /api/v1
spring:
  application:
    name: PizzaHut-be
  cache:
    type: redis
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
      password:
      db-default: 0
      timeout: 60000
  jwt:
    secret: ${JWT-SECRET:XbHRcgAojNcOjzZkDZpZZp3o4oAr7rphVgF2J4r7XbnwvczlhWbRnN9gZ1RMkhObl9hXzwAW1qXMIqUXoUGyFH6JQkVvGgVka31gWJ8o9UCnqhKvRQIw3gOURsWwdGaGWM7rTM3TCEC7peVbPfnUCwSJ6GAbGVVA0QcUu5gDVe16eazgh44j8O9CDgpfNEb0SoCBUiUkAgiZaO9J1xwVQekdAQy3Sz2KRbg0nqI7rbP9Jz0iFygG4tvvvcV2U34eHxryGd4dXJerfpNZmJS4EOwWA4OS6zuYnFGBymwFT6CRVEE8qB}
    expire: ${JWT-EXPiRE:1209600000}
  messages:
    encoding: UTF-8
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:pizzahutproject.net@gmail.com}
    password: ${MAIL_PASSWORD:mgxx kbhr tcki ifbr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  otp:
    destination:
      default: PHONE
    expire-time:
      default: 180
database:
  jdbcUrl : ${DB_URL:jdbc:mysql://localhost:3306/pizza_project_data}
  username: ${DB_USERNAME:root}
  password: ${DB_PASSWORD:11102002}

hikari:
  minimum-idle: 15
  maximum-pool-size: 250
  idle-timeout: 30000
  max-lifetime: 1800000
  connection-test-query: SELECT 1
  pool-name: ApiAppHikariPool
  driverClass: org.mariadb.jdbc.Driver
minio:
  url:
    public: ${ENDPOINT:http://localhost:9000}
  access:
    key: minio
  secret:
    key: miniostorage
  bucket: images
  region: us-east-1
  secure: false
#Swagger ui enabled
springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI_ENABLED:true}
#config login google sso
google:
  client:
    id: ${GOOGLE_ID:392422801-urmoaa07figp0khtqmlac2us0ojtvelf.apps.googleusercontent.com}
    secret: ${GOOGLE_SECRET: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}
  redirect:
    uri: ${GOOGLE_URI:http://localhost:8080}
  token:
    path: "https://oauth2.googleapis.com/token"

